### ISSUE TITLE
Database name different in log continuously

### ISSUE THREAD

**Issue by gazoutg** [kebman/log-ic#1]
The database filename the script open is different in log_IC_continously
it is ic_log1_2020-**06-30**_manual.db everywhere but in log_IC_continously it's  ic_log1_2020-**08-01**_manual.db

**Comment by kebman** [comment]
Thanks for your reply. I'm afraid you're just going to have to change the filenames for the *.db files manually in the relevant Python scripts. Sorry for this.

As you can see, they're named with the date they were started. I did this to document when I did the polling. 

Eventually the ISP sent a technician to fix my connection, and I no longer needed these scripts to document the outages, and I've since moved from the location. As such I no longer have any use for this project, and the scripts are provided as is. Really happy you showed interest in the project though! :)
